#!/bin/sh

case "$1" in
"a")
	sed '1i\
/*
$a\
*/
'
	;;
"b")
	sed '1i\
#if 0
$a\
#endif
'
	;;
"c")
	sed 's,^,// ,g'
	;;
"d")
	sed 's/^/# /g'
	;;
"e")
	sed 's/^/% /g'
	;;
*)
	[ "$1" != "" ] || set "/"
	[ "$2" != "" ] || set $1 "/"
	sed '1i\
'$1'*
$a\
 *'$2'
1,$s/^/ * /g
'
esac
